#sonar params
use_sonar: false
a00: 0.0
a01: 0.5
a10: 0.3
a11: 0.9
a20: 0.8
a21: 0.6
a30: 0.8
a31: 0.6
asonar: 2.0

a_theta: 0.99
b_alpha: 0.1
c_dist: 0.125

max_vx: 0.5
max_rz: 0.87
min_turn_radius: 0
#1.25

#robot's width and robot's safe gap distance
robot_width: 0.15
robot_safe_gap: 0.2

# detection tolarence of obstacles, the smaller the stricter
det_tolerance: 3

# max distance error between two edges of safezone
safezone_rest_wide: 10.8

# max direction error between goal and nearest safe zone
largest_err_direction: 1.57

# min range error of a safezone = min_err_range_sz * range_step_size (m)
min_err_range_sz: 3

# width threshold(m) for safezone detection = lvlerrthreshold_of_sz * range_step_size, least 1
safezone_lvl_err_threshold: 1

# absolute safe distance = lvlabsulute_safe * range_step_size
lvl_absulute_safe: 0.5

#half field of view(rad), 0.52rad=30degree
half_fov: 1.52

#lidar
use_lidar: true
view_safezone_lidar: true
# detect range(m) = range_step_size(m) * obs_timesofdeld, both 3d and 2d lidar
obs_times_of_deld: 25
# step size of each step in range in one direction, 2d
range_step_size: 0.1
# obs detect increment angle(rad) around z axix, both 3d and 2d lidar
obs_dangle: 0.005
# diameter of search circle diameter, both 3d and 2d lidar
deld: 0.6
# max turn speed default pi/2
oa_max_angular_speed: 1.5708
# tell program that data from -time_of_halfpi*pi/2 to time_of_halfpi*pi/2 is ok
# for 2d and 3d lidar
time_of_halfpi: 1.5

#3d lidar
use_lidar3d: false
view_safezone_lidar3d: false
# start detection height of 3dlidar frame
initial_height_of_lidar3d: 0.0
# lidar's translation from base_link(m), for both 3d and 2d lidar
lidar_x: 0.25
lidar_y: 0
lidar_z: 0
#num of scan layer
num_of_layers: 1
#dead zone, radius of circle around robot you want to ignore
deadzone: 0.0

#tof
use_tof: false
view_safezone_tof: false
# detect range(m) = deld(m) * timesofdeld
obs_times_of_deld_tof: 5
# obs detect increment angle(rad)
obs_dangle_tof: 0.035
# search circle diameter
deld_tof: 0.46
# start detection height of camera frame
initial_height_of_cam: -0.42

# datatype for viewer 3d
#1-tof,rgbd
#2-3d lidar
data_type: 2
